#!/usr/bin/env bash
# Regenerate services/ui-neu/frontend/src/lib/types/api.gen.ts from the v3
# Backend's committed OpenAPI snapshot (services/ui-neu/openapi.snapshot.json),
# then run the Node generator. Pre-commit hook and CI codegen-check invoke this.
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"

# v3 owns the contract: generate from the Backend's committed OpenAPI snapshot,
# NOT the old BFF app.
V3_SNAPSHOT="$REPO_ROOT/services/ui-neu/openapi.snapshot.json"
if [ ! -f "$V3_SNAPSHOT" ]; then
    echo "v3 OpenAPI snapshot not found at $V3_SNAPSHOT" >&2
    exit 1
fi
TMPSCHEMA="$V3_SNAPSHOT"

cd "$REPO_ROOT/services/ui-neu/frontend"

# `tsconfig.json` extends `./.svelte-kit/tsconfig.json`, a build artifact that
# only exists after a SvelteKit sync/build. @hey-api/openapi-ts reads tsconfig
# during output resolution, so on a fresh checkout (CI after bare `npm ci`, no
# dev/build run yet) the missing `extends` target makes codegen fail with
# "Couldn't read tsconfig". Generate it first so codegen is reproducible.
npx svelte-kit sync

npx --yes @hey-api/openapi-ts \
    --input "$TMPSCHEMA" \
    --output src/lib/types/api.gen.ts \
    --plugins @hey-api/typescript

# Banner. Generator emits its own header but a project-specific reminder
# helps editors clicking into the file before any manual edit.
TARGET="$REPO_ROOT/services/ui-neu/frontend/src/lib/types/api.gen.ts"
if [ -f "$TARGET" ]; then
    sed -i '1i // Generated by scripts/codegen.sh - DO NOT EDIT' "$TARGET"
elif [ -f "$REPO_ROOT/services/ui-neu/frontend/src/lib/types/api.gen.ts/types.gen.ts" ]; then
    # hey-api may emit a directory; rename and banner the inner file.
    mv "$REPO_ROOT/services/ui-neu/frontend/src/lib/types/api.gen.ts" \
       "$REPO_ROOT/services/ui-neu/frontend/src/lib/types/api.gen.tmp"
    mv "$REPO_ROOT/services/ui-neu/frontend/src/lib/types/api.gen.tmp/types.gen.ts" "$TARGET"
    rm -rf "$REPO_ROOT/services/ui-neu/frontend/src/lib/types/api.gen.tmp"
    sed -i '1i // Generated by scripts/codegen.sh - DO NOT EDIT' "$TARGET"
fi
