import type { SettingsSchemaResponse } from '$lib/types/api.gen';

// GET /api/settings/schema as the backend serves it: generated from
// arm_common.config_metadata.CONFIG_FIELD_META (group order from
// arm_backend.routers.settings._GROUP_ORDER). Regenerate when the field
// metadata changes so the settings screenshots keep tracking the real tabs.
export const settingsSchema: SettingsSchemaResponse = {
	groups: [
		{
			name: 'Metadata',
			fields: [
				{
					key: 'metadata_provider',
					group: 'Metadata',
					tier: 'operator',
					label: 'Look up titles with',
					help: 'The service ARM searches when it identifies a disc.',
					type: 'enum',
					editable: true,
					enum_values: ['tmdb', 'omdb'],
					enum_labels: {
						tmdb: 'TMDb',
						omdb: 'OMDb'
					},
					enum_requires: null,
					setup_step: 'metadata',
					setup_order: 4,
					signup_url: null,
					widget: null,
					part_of: null
				},
				{
					key: 'tmdb_api_key',
					group: 'Metadata',
					tier: 'secret',
					label: 'TMDb API key',
					help: 'The Movie Database API key (free; recommended).',
					type: 'string',
					editable: true,
					enum_values: null,
					enum_labels: null,
					enum_requires: null,
					setup_step: 'metadata',
					setup_order: 1,
					signup_url: 'https://www.themoviedb.org/settings/api',
					widget: null,
					part_of: null
				},
				{
					key: 'omdb_api_key',
					group: 'Metadata',
					tier: 'secret',
					label: 'OMDb API key',
					help: 'Open Movie Database API key (1000 req/day free tier).',
					type: 'string',
					editable: true,
					enum_values: null,
					enum_labels: null,
					enum_requires: null,
					setup_step: 'metadata',
					setup_order: 2,
					signup_url: 'https://www.omdbapi.com/apikey.aspx',
					widget: null,
					part_of: null
				},
				{
					key: 'tvdb_api_key',
					group: 'Metadata',
					tier: 'secret',
					label: 'TVDb API key',
					help: 'Needed for the TVDB episode source.',
					type: 'string',
					editable: true,
					enum_values: null,
					enum_labels: null,
					enum_requires: null,
					setup_step: 'metadata',
					setup_order: 3,
					signup_url: 'https://thetvdb.com/api-information',
					widget: null,
					part_of: null
				},
				{
					key: 'makemkv_key',
					group: 'Metadata',
					tier: 'secret',
					label: 'MakeMKV key',
					help: 'MakeMKV registration key (purchased perma-key or beta key).',
					type: 'string',
					editable: true,
					enum_values: null,
					enum_labels: null,
					enum_requires: null,
					setup_step: 'makemkv',
					setup_order: 1,
					signup_url: null,
					widget: 'makemkv_key',
					part_of: null
				},
				{
					key: 'thediscdb_enabled',
					group: 'Metadata',
					tier: 'operator',
					label: 'Match discs against TheDiscDB',
					help: 'Match discs against the local TheDiscDB snapshot to label titles, pick the main feature, and name extras/episodes.',
					type: 'bool',
					editable: true,
					enum_values: null,
					enum_labels: null,
					enum_requires: null,
					setup_step: 'metadata',
					setup_order: 5,
					signup_url: null,
					widget: null,
					part_of: null
				},
				{
					key: 'thediscdb_refresh_days',
					group: 'Metadata',
					tier: 'operator',
					label: 'TheDiscDB refresh interval (days)',
					help: 'How often the backend refreshes its TheDiscDB snapshot from GitHub.',
					type: 'int',
					editable: true,
					enum_values: null,
					enum_labels: null,
					enum_requires: null,
					setup_step: null,
					setup_order: null,
					signup_url: null,
					widget: null,
					part_of: null
				},
				{
					key: 'episode_sources',
					group: 'Metadata',
					tier: 'operator',
					label: 'Episode sources',
					help: 'Tried top to bottom. ARM stops at the first confident match. TVmaze needs no key.',
					type: 'ranked',
					editable: true,
					enum_values: ['tmdb', 'tvmaze', 'tvdb'],
					enum_labels: {
						tmdb: 'TMDb',
						tvmaze: 'TVmaze',
						tvdb: 'TVDB'
					},
					enum_requires: {
						tmdb: 'tmdb_api_key',
						tvdb: 'tvdb_api_key'
					},
					setup_step: null,
					setup_order: null,
					signup_url: null,
					widget: null,
					part_of: null
				},
				{
					key: 'disc_hint_sources',
					group: 'Metadata',
					tier: 'operator',
					label: 'Read season and disc number from',
					help: 'Read from the disc in this order, before ARM identifies it.',
					type: 'ranked',
					editable: true,
					enum_values: ['bd_title', 'label'],
					enum_labels: {
						bd_title: 'Blu-ray disc title',
						label: 'Disc volume label'
					},
					enum_requires: null,
					setup_step: null,
					setup_order: null,
					signup_url: null,
					widget: null,
					part_of: null
				},
				{
					key: 'episode_match_tolerance_seconds',
					group: 'Metadata',
					tier: 'operator',
					label: 'Match tolerance (seconds)',
					help: "The most a track's runtime may differ from an episode's and still match. ARM narrows this to a tenth of the episode's runtime, at least 60 seconds. 1 to 1800, default 300.",
					type: 'int',
					editable: true,
					enum_values: null,
					enum_labels: null,
					enum_requires: null,
					setup_step: null,
					setup_order: null,
					signup_url: null,
					widget: null,
					part_of: null
				},
				{
					key: 'episode_auto_apply',
					group: 'Metadata',
					tier: 'operator',
					label: 'Apply confident matches',
					help: 'When off, every match is kept as a suggestion to review on the job page.',
					type: 'bool',
					editable: true,
					enum_values: null,
					enum_labels: null,
					enum_requires: null,
					setup_step: null,
					setup_order: null,
					signup_url: null,
					widget: null,
					part_of: null
				}
			]
		},
		{
			name: 'Ripping',
			fields: [
				{
					key: 'auto_rip_on_insert',
					group: 'Ripping',
					tier: 'operator',
					label: 'Auto-rip on insert',
					help: 'Start ripping automatically when a disc is detected.',
					type: 'bool',
					editable: true,
					enum_values: null,
					enum_labels: null,
					enum_requires: null,
					setup_step: 'discs',
					setup_order: 1,
					signup_url: null,
					widget: 'disc_handling',
					part_of: null
				},
				{
					key: 'block_on_miss',
					group: 'Ripping',
					tier: 'operator',
					label: 'Block on metadata miss',
					help: 'Hold a job for manual ID when no metadata match is found.',
					type: 'bool',
					editable: true,
					enum_values: null,
					enum_labels: null,
					enum_requires: null,
					setup_step: null,
					setup_order: null,
					signup_url: null,
					widget: null,
					part_of: null
				},
				{
					key: 'community_keydb_enabled',
					group: 'Ripping',
					tier: 'operator',
					label: 'Download community decryption keys (KEYDB)',
					help: "Opens Blu-rays MakeMKV can't decrypt on its own, using keys shared by other users (FindVUK).",
					type: 'bool',
					editable: true,
					enum_values: null,
					enum_labels: null,
					enum_requires: null,
					setup_step: 'makemkv',
					setup_order: 2,
					signup_url: null,
					widget: null,
					part_of: null
				},
				{
					key: 'makemkv_sdf_enabled',
					group: 'Ripping',
					tier: 'operator',
					label: "Use MakeMKV's disc format updates (SDF)",
					help: 'Keeps MakeMKV able to read disc formats released after this version. A baseline ships in the image; this keeps it current.',
					type: 'bool',
					editable: true,
					enum_values: null,
					enum_labels: null,
					enum_requires: null,
					setup_step: 'makemkv',
					setup_order: 3,
					signup_url: null,
					widget: null,
					part_of: null
				},
				{
					key: 'ripping_paused',
					group: 'Ripping',
					tier: 'operator',
					label: 'Pause new rips',
					help: 'Reject new rip jobs (in-flight rips continue).',
					type: 'bool',
					editable: true,
					enum_values: null,
					enum_labels: null,
					enum_requires: null,
					setup_step: null,
					setup_order: null,
					signup_url: null,
					widget: null,
					part_of: null
				},
				{
					key: 'hold_for_review',
					group: 'Ripping',
					tier: 'operator',
					label: 'Hold discs for review',
					help: 'Hold each inserted disc in a timed review state after scan + identify, so you can correct it before the rip starts. The rip auto-starts when the countdown ends (unless rips are paused).',
					type: 'bool',
					editable: true,
					enum_values: null,
					enum_labels: null,
					enum_requires: null,
					setup_step: null,
					setup_order: null,
					signup_url: null,
					widget: null,
					part_of: 'auto_rip_on_insert'
				},
				{
					key: 'manual_wait_seconds',
					group: 'Ripping',
					tier: 'operator',
					label: 'Review countdown (seconds)',
					help: 'How long a held disc waits for review before the rip auto-starts.',
					type: 'int',
					editable: true,
					enum_values: null,
					enum_labels: null,
					enum_requires: null,
					setup_step: null,
					setup_order: null,
					signup_url: null,
					widget: null,
					part_of: null
				},
				{
					key: 'max_parallel_iso_rips',
					group: 'Ripping',
					tier: 'operator',
					label: 'Max parallel ISO rips',
					help: 'How many ISO files can rip at the same time, 1 to 8. Each runs its own ripper.',
					type: 'int',
					editable: true,
					enum_values: null,
					enum_labels: null,
					enum_requires: null,
					setup_step: null,
					setup_order: null,
					signup_url: null,
					widget: null,
					part_of: null
				}
			]
		},
		{
			name: 'Transcoding',
			fields: [
				{
					key: 'transcode_enabled',
					group: 'Transcoding',
					tier: 'operator',
					label: 'Enable transcoding',
					help: 'Master switch for encode work. Off: no new encode tasks are created or spawned; queued ones are held and resume when re-enabled. Passthrough sessions (plain file moves into the library) keep working either way.',
					type: 'bool',
					editable: true,
					enum_values: null,
					enum_labels: null,
					enum_requires: null,
					setup_step: 'transcoding',
					setup_order: 1,
					signup_url: null,
					widget: null,
					part_of: null
				},
				{
					key: 'transcode_capable',
					group: 'Transcoding',
					tier: 'infra',
					label: 'Transcode capable',
					help: 'Whether this deployment can run transcode containers at all (set at install time; a ripper-only install is not capable).',
					type: 'bool',
					editable: false,
					enum_values: null,
					enum_labels: null,
					enum_requires: null,
					setup_step: null,
					setup_order: null,
					signup_url: null,
					widget: null,
					part_of: null
				},
				{
					key: 'auto_transcode_on_idle',
					group: 'Transcoding',
					tier: 'operator',
					label: 'Auto-apply default session after rip',
					help: "When a rip completes, automatically apply the drive's default session (queue its transcodes). An explicit per-rip session choice always applies, and the default session still shapes the rip either way.",
					type: 'bool',
					editable: true,
					enum_values: null,
					enum_labels: null,
					enum_requires: null,
					setup_step: null,
					setup_order: null,
					signup_url: null,
					widget: null,
					part_of: null
				},
				{
					key: 'max_parallel_transcodes',
					group: 'Transcoding',
					tier: 'operator',
					label: 'Max parallel transcodes',
					help: 'Concurrent transcode containers. Applies from the next dispatcher tick; the MAX_PARALLEL_TRANSCODES env value only seeds this once.',
					type: 'int',
					editable: true,
					enum_values: null,
					enum_labels: null,
					enum_requires: null,
					setup_step: 'transcoding',
					setup_order: 2,
					signup_url: null,
					widget: null,
					part_of: null
				}
			]
		},
		{
			name: 'Notifications',
			fields: [
				{
					key: 'notifications_enabled',
					group: 'Notifications',
					tier: 'operator',
					label: 'Enable notifications',
					help: 'Master toggle for outbound notification dispatch.',
					type: 'bool',
					editable: true,
					enum_values: null,
					enum_labels: null,
					enum_requires: null,
					setup_step: null,
					setup_order: null,
					signup_url: null,
					widget: null,
					part_of: null
				}
			]
		},
		{
			name: 'System',
			fields: [
				{
					key: 'MEDIA_ROOT',
					group: 'System',
					tier: 'infra',
					label: 'Media root',
					help: 'Container path where finished media is written.',
					type: 'string',
					editable: false,
					enum_values: null,
					enum_labels: null,
					enum_requires: null,
					setup_step: null,
					setup_order: null,
					signup_url: null,
					widget: null,
					part_of: null
				},
				{
					key: 'RAW_ROOT',
					group: 'System',
					tier: 'infra',
					label: 'Raw root',
					help: 'Container path for per-job raw rips.',
					type: 'string',
					editable: false,
					enum_values: null,
					enum_labels: null,
					enum_requires: null,
					setup_step: null,
					setup_order: null,
					signup_url: null,
					widget: null,
					part_of: null
				},
				{
					key: 'ISO_INGRESS_ROOT',
					group: 'System',
					tier: 'infra',
					label: 'ISO ingress root',
					help: 'Sandbox path for ISO-import scanning.',
					type: 'string',
					editable: false,
					enum_values: null,
					enum_labels: null,
					enum_requires: null,
					setup_step: null,
					setup_order: null,
					signup_url: null,
					widget: null,
					part_of: null
				},
				{
					key: 'BIND_PORT',
					group: 'System',
					tier: 'infra',
					label: 'Bind port',
					help: 'Backend HTTPS listen port.',
					type: 'string',
					editable: false,
					enum_values: null,
					enum_labels: null,
					enum_requires: null,
					setup_step: null,
					setup_order: null,
					signup_url: null,
					widget: null,
					part_of: null
				},
				{
					key: 'drive_scan_interval_seconds',
					group: 'System',
					tier: 'operator',
					label: 'Drive scan interval (seconds)',
					help: 'How often the backend re-enumerates optical drives from sysfs.',
					type: 'int',
					editable: true,
					enum_values: null,
					enum_labels: null,
					enum_requires: null,
					setup_step: null,
					setup_order: null,
					signup_url: null,
					widget: null,
					part_of: null
				},
				{
					key: 'drive_detected_prune_days',
					group: 'System',
					tier: 'operator',
					label: 'Forget unseen drives after (days)',
					help: 'Detected-but-never-enrolled drives absent this long are dropped from the list.',
					type: 'int',
					editable: true,
					enum_values: null,
					enum_labels: null,
					enum_requires: null,
					setup_step: null,
					setup_order: null,
					signup_url: null,
					widget: null,
					part_of: null
				},
				{
					key: 'ARM_DOCKER_NETWORK',
					group: 'System',
					tier: 'infra',
					label: 'Docker network',
					help: 'Network the spawned transcoders join.',
					type: 'string',
					editable: false,
					enum_values: null,
					enum_labels: null,
					enum_requires: null,
					setup_step: null,
					setup_order: null,
					signup_url: null,
					widget: null,
					part_of: null
				},
				{
					key: 'ARM_GPUS',
					group: 'System',
					tier: 'infra',
					label: 'GPU inventory',
					help: 'GPUs detected host-side at install (empty = CPU-only).',
					type: 'string',
					editable: false,
					enum_values: null,
					enum_labels: null,
					enum_requires: null,
					setup_step: null,
					setup_order: null,
					signup_url: null,
					widget: null,
					part_of: null
				}
			]
		}
	]
};
